const data = [
  {
    department: "Engineering",
    company: "Browsecat",
    gender: "Male",
    language: "Norwegian",
    first_name: "Edward",
    ssn: "843-29-9196",
  },
  {
    department: "Sales",
    company: "Plajo",
    gender: "Male",
    language: "Lao",
    first_name: "Rupert",
    ssn: "357-08-8965",
  },
  {
    department: "Sales",
    company: "Linkbridge",
    gender: "Male",
    language: "Hungarian",
    first_name: "Brandon",
    ssn: "414-23-1322",
  },
  {
    department: "Legal",
    company: "Chatterpoint",
    gender: "Female",
    language: "Afrikaans",
    first_name: "Lind",
    ssn: "884-31-3985",
  },
  {
    department: "Business Development",
    company: "Vinte",
    gender: "Female",
    language: "Maltese",
    first_name: "Dyanne",
    ssn: "307-51-7465",
  },
  {
    department: "Marketing",
    company: "Dabjam",
    gender: "Female",
    language: "Guaraní",
    first_name: "Noami",
    ssn: "640-39-3483",
  },
  {
    department: "Sales",
    company: "Youtags",
    gender: "Male",
    language: "Pashto",
    first_name: "Hobey",
    ssn: "111-76-3318",
  },
  {
    department: "Marketing",
    company: "Skiba",
    gender: "Male",
    language: "Swahili",
    first_name: "Giraud",
    ssn: "392-78-9516",
  },
  {
    department: "Support",
    company: "Dabfeed",
    gender: "Female",
    language: "Swati",
    first_name: "Rosamund",
    ssn: "639-56-2972",
  },
  {
    department: "Sales",
    company: "Meevee",
    gender: "Male",
    language: "Kazakh",
    first_name: "Curry",
    ssn: "264-37-6083",
  },
  {
    department: "Sales",
    company: "Flashspan",
    gender: "Female",
    language: "Telugu",
    first_name: "Aggy",
    ssn: "400-04-5027",
  },
  {
    department: "Services",
    company: "Skyba",
    gender: "Male",
    language: "Finnish",
    first_name: "Hillard",
    ssn: "868-41-5812",
  },
  {
    department: "Support",
    company: "Avamm",
    gender: "Male",
    language: "Icelandic",
    first_name: "Spenser",
    ssn: "163-95-2046",
  },
  {
    department: "Engineering",
    company: "Quinu",
    gender: "Female",
    language: "Bulgarian",
    first_name: "Clea",
    ssn: "557-99-0617",
  },
  {
    department: "Human Resources",
    company: "Eidel",
    gender: "Polygender",
    language: "Hebrew",
    first_name: "Lizabeth",
    ssn: "219-95-7029",
  },
  {
    department: "Training",
    company: "Meembee",
    gender: "Male",
    language: "Portuguese",
    first_name: "Dame",
    ssn: "562-09-2168",
  },
  {
    department: "Accounting",
    company: "Plambee",
    gender: "Male",
    language: "Thai",
    first_name: "Osbourn",
    ssn: "787-63-5925",
  },
  {
    department: "Engineering",
    company: "Vidoo",
    gender: "Male",
    language: "Danish",
    first_name: "Fletcher",
    ssn: "739-60-4776",
  },
  {
    department: "Sales",
    company: "Youspan",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Jed",
    ssn: "259-12-8310",
  },
  {
    department: "Services",
    company: "Agimba",
    gender: "Male",
    language: "Korean",
    first_name: "Dun",
    ssn: "207-70-7032",
  },
  {
    department: "Sales",
    company: "Dabshots",
    gender: "Female",
    language: "Finnish",
    first_name: "Alma",
    ssn: "595-14-9030",
  },
  {
    department: "Legal",
    company: "Devcast",
    gender: "Non-binary",
    language: "West Frisian",
    first_name: "Verla",
    ssn: "542-55-3389",
  },
  {
    department: "Product Management",
    company: "Trilith",
    gender: "Male",
    language: "Marathi",
    first_name: "Rodney",
    ssn: "413-31-8090",
  },
  {
    department: "Training",
    company: "Livetube",
    gender: "Non-binary",
    language: "Sotho",
    first_name: "Pierre",
    ssn: "545-83-7505",
  },
  {
    department: "Engineering",
    company: "Brainlounge",
    gender: "Male",
    language: "Hungarian",
    first_name: "Reilly",
    ssn: "286-02-3617",
  },
  {
    department: "Services",
    company: "Voonte",
    gender: "Male",
    language: "Malayalam",
    first_name: "Bronnie",
    ssn: "284-11-3710",
  },
  {
    department: "Business Development",
    company: "Lajo",
    gender: "Female",
    language: "Bislama",
    first_name: "Gus",
    ssn: "147-72-5467",
  },
  {
    department: "Sales",
    company: "Bubblebox",
    gender: "Male",
    language: "Georgian",
    first_name: "Emory",
    ssn: "715-59-5467",
  },
  {
    department: "Research and Development",
    company: "Brainsphere",
    gender: "Female",
    language: "Kannada",
    first_name: "Morna",
    ssn: "281-48-7385",
  },
  {
    department: "Training",
    company: "Ntags",
    gender: "Male",
    language: "Punjabi",
    first_name: "Brian",
    ssn: "653-62-6711",
  },
  {
    department: "Research and Development",
    company: "Tagcat",
    gender: "Male",
    language: "Lao",
    first_name: "Webb",
    ssn: "622-14-0510",
  },
  {
    department: "Product Management",
    company: "Tambee",
    gender: "Female",
    language: "Azeri",
    first_name: "Ange",
    ssn: "413-78-9042",
  },
  {
    department: "Sales",
    company: "Skyvu",
    gender: "Female",
    language: "Oriya",
    first_name: "Noel",
    ssn: "739-40-5638",
  },
  {
    department: "Legal",
    company: "Thoughtstorm",
    gender: "Female",
    language: "French",
    first_name: "Tera",
    ssn: "576-05-2434",
  },
  {
    department: "Legal",
    company: "Skaboo",
    gender: "Male",
    language: "Finnish",
    first_name: "Ignaz",
    ssn: "739-62-3347",
  },
  {
    department: "Legal",
    company: "Bubblemix",
    gender: "Female",
    language: "Nepali",
    first_name: "Louise",
    ssn: "340-97-5850",
  },
  {
    department: "Training",
    company: "Izio",
    gender: "Male",
    language: "Burmese",
    first_name: "Karlan",
    ssn: "272-81-5777",
  },
  {
    department: "Research and Development",
    company: "Wikido",
    gender: "Female",
    language: "Haitian Creole",
    first_name: "Flossy",
    ssn: "796-09-0451",
  },
  {
    department: "Product Management",
    company: "Centimia",
    gender: "Male",
    language: "Dutch",
    first_name: "Sloan",
    ssn: "141-49-9769",
  },
  {
    department: "Business Development",
    company: "Wordify",
    gender: "Female",
    language: "Tetum",
    first_name: "Jane",
    ssn: "696-30-9758",
  },
  {
    department: "Human Resources",
    company: "Skipfire",
    gender: "Female",
    language: "Malay",
    first_name: "Melodie",
    ssn: "433-72-8051",
  },
  {
    department: "Accounting",
    company: "Devbug",
    gender: "Male",
    language: "Malay",
    first_name: "Olly",
    ssn: "375-86-0032",
  },
  {
    department: "Accounting",
    company: "Youspan",
    gender: "Female",
    language: "Aymara",
    first_name: "Erica",
    ssn: "484-31-6276",
  },
  {
    department: "Services",
    company: "Avavee",
    gender: "Female",
    language: "Japanese",
    first_name: "Ede",
    ssn: "364-06-7710",
  },
  {
    department: "Human Resources",
    company: "Bluezoom",
    gender: "Female",
    language: "Swahili",
    first_name: "Timmi",
    ssn: "211-39-6831",
  },
  {
    department: "Business Development",
    company: "Realcube",
    gender: "Female",
    language: "Afrikaans",
    first_name: "Vivianne",
    ssn: "286-22-0522",
  },
  {
    department: "Marketing",
    company: "Gigazoom",
    gender: "Female",
    language: "Macedonian",
    first_name: "Elbertina",
    ssn: "503-13-8414",
  },
  {
    department: "Business Development",
    company: "Wordware",
    gender: "Male",
    language: "Oriya",
    first_name: "Ced",
    ssn: "670-95-1890",
  },
  {
    department: "Training",
    company: "Youfeed",
    gender: "Male",
    language: "Mongolian",
    first_name: "Simeon",
    ssn: "671-53-4141",
  },
  {
    department: "Product Management",
    company: "Avamm",
    gender: "Polygender",
    language: "Chinese",
    first_name: "Kristos",
    ssn: "592-96-3166",
  },
  {
    department: "Training",
    company: "Fatz",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Raff",
    ssn: "224-76-9964",
  },
  {
    department: "Engineering",
    company: "Katz",
    gender: "Female",
    language: "Albanian",
    first_name: "Glennie",
    ssn: "339-16-5866",
  },
  {
    department: "Support",
    company: "Topicware",
    gender: "Female",
    language: "Malagasy",
    first_name: "Sophie",
    ssn: "676-46-3971",
  },
  {
    department: "Accounting",
    company: "Quatz",
    gender: "Male",
    language: "Hebrew",
    first_name: "Basile",
    ssn: "513-57-7128",
  },
  {
    department: "Services",
    company: "Podcat",
    gender: "Male",
    language: "Icelandic",
    first_name: "Wallas",
    ssn: "824-07-3086",
  },
  {
    department: "Sales",
    company: "Zazio",
    gender: "Female",
    language: "Dutch",
    first_name: "Davida",
    ssn: "649-88-6978",
  },
  {
    department: "Services",
    company: "Einti",
    gender: "Male",
    language: "Pashto",
    first_name: "Wat",
    ssn: "353-65-2492",
  },
  {
    department: "Human Resources",
    company: "Fatz",
    gender: "Female",
    language: "Kazakh",
    first_name: "Julienne",
    ssn: "449-95-4339",
  },
  {
    department: "Product Management",
    company: "Fiveclub",
    gender: "Male",
    language: "Kyrgyz",
    first_name: "Erich",
    ssn: "239-03-4112",
  },
  {
    department: "Research and Development",
    company: "Voomm",
    gender: "Female",
    language: "Macedonian",
    first_name: "Blanca",
    ssn: "469-17-4246",
  },
  {
    department: "Sales",
    company: "Feedfish",
    gender: "Female",
    language: "Somali",
    first_name: "Pauly",
    ssn: "364-70-2798",
  },
  {
    department: "Marketing",
    company: "Realfire",
    gender: "Female",
    language: "Kurdish",
    first_name: "Tamiko",
    ssn: "602-95-9373",
  },
  {
    department: "Marketing",
    company: "Pixonyx",
    gender: "Female",
    language: "Irish Gaelic",
    first_name: "Imogen",
    ssn: "822-45-0733",
  },
  {
    department: "Marketing",
    company: "Oyope",
    gender: "Male",
    language: "Tajik",
    first_name: "Myca",
    ssn: "445-16-3638",
  },
  {
    department: "Research and Development",
    company: "Devshare",
    gender: "Female",
    language: "Oriya",
    first_name: "Madelena",
    ssn: "567-66-2459",
  },
  {
    department: "Engineering",
    company: "Tambee",
    gender: "Male",
    language: "Bislama",
    first_name: "Carce",
    ssn: "721-60-3198",
  },
  {
    department: "Training",
    company: "Innojam",
    gender: "Male",
    language: "Arabic",
    first_name: "Kareem",
    ssn: "635-89-7342",
  },
  {
    department: "Marketing",
    company: "Buzzster",
    gender: "Female",
    language: "Māori",
    first_name: "Loella",
    ssn: "699-69-9016",
  },
  {
    department: "Training",
    company: "Realmix",
    gender: "Female",
    language: "Italian",
    first_name: "Karalynn",
    ssn: "830-46-1120",
  },
  {
    department: "Product Management",
    company: "Linkbridge",
    gender: "Male",
    language: "Catalan",
    first_name: "Nickolas",
    ssn: "134-08-2522",
  },
  {
    department: "Marketing",
    company: "Brainsphere",
    gender: "Female",
    language: "Northern Sotho",
    first_name: "Sam",
    ssn: "167-45-6468",
  },
  {
    department: "Marketing",
    company: "Dabtype",
    gender: "Male",
    language: "Quechua",
    first_name: "Howie",
    ssn: "281-21-2345",
  },
  {
    department: "Legal",
    company: "Bluezoom",
    gender: "Female",
    language: "Afrikaans",
    first_name: "Jannelle",
    ssn: "278-72-9478",
  },
  {
    department: "Product Management",
    company: "Photobean",
    gender: "Female",
    language: "Dutch",
    first_name: "Hedvige",
    ssn: "189-08-2617",
  },
  {
    department: "Accounting",
    company: "Twitternation",
    gender: "Genderfluid",
    language: "Indonesian",
    first_name: "Jonathan",
    ssn: "205-85-4241",
  },
  {
    department: "Business Development",
    company: "Realcube",
    gender: "Male",
    language: "Hungarian",
    first_name: "Germain",
    ssn: "816-61-1774",
  },
  {
    department: "Accounting",
    company: "Gigabox",
    gender: "Male",
    language: "Romanian",
    first_name: "Base",
    ssn: "145-74-1562",
  },
  {
    department: "Human Resources",
    company: "Buzzbean",
    gender: "Female",
    language: "Papiamento",
    first_name: "Leshia",
    ssn: "250-11-7523",
  },
  {
    department: "Human Resources",
    company: "Kwimbee",
    gender: "Female",
    language: "Marathi",
    first_name: "Magdalena",
    ssn: "694-36-5994",
  },
  {
    department: "Services",
    company: "Mita",
    gender: "Male",
    language: "Afrikaans",
    first_name: "Loren",
    ssn: "893-89-5057",
  },
  {
    department: "Engineering",
    company: "Kazio",
    gender: "Female",
    language: "Tok Pisin",
    first_name: "Lorie",
    ssn: "775-49-5378",
  },
  {
    department: "Research and Development",
    company: "Twimm",
    gender: "Female",
    language: "German",
    first_name: "Roxana",
    ssn: "152-90-3266",
  },
  {
    department: "Sales",
    company: "Wordify",
    gender: "Female",
    language: "Azeri",
    first_name: "Cherida",
    ssn: "632-59-8385",
  },
  {
    department: "Product Management",
    company: "Zooveo",
    gender: "Polygender",
    language: "West Frisian",
    first_name: "Derward",
    ssn: "506-11-3215",
  },
  {
    department: "Training",
    company: "Vinder",
    gender: "Female",
    language: "Polish",
    first_name: "Larina",
    ssn: "609-44-8071",
  },
  {
    department: "Accounting",
    company: "Zoovu",
    gender: "Male",
    language: "Korean",
    first_name: "Basilio",
    ssn: "602-52-4987",
  },
  {
    department: "Training",
    company: "Zoomcast",
    gender: "Bigender",
    language: "Swahili",
    first_name: "Katine",
    ssn: "708-79-6954",
  },
  {
    department: "Services",
    company: "Photospace",
    gender: "Polygender",
    language: "Catalan",
    first_name: "Richmound",
    ssn: "265-43-4194",
  },
  {
    department: "Marketing",
    company: "Realmix",
    gender: "Female",
    language: "Hindi",
    first_name: "Lindi",
    ssn: "430-59-4566",
  },
  {
    department: "Legal",
    company: "Photojam",
    gender: "Female",
    language: "Korean",
    first_name: "Erin",
    ssn: "276-63-3308",
  },
  {
    department: "Research and Development",
    company: "Katz",
    gender: "Female",
    language: "Ndebele",
    first_name: "Lira",
    ssn: "225-62-0473",
  },
  {
    department: "Sales",
    company: "Jatri",
    gender: "Female",
    language: "Persian",
    first_name: "Eveline",
    ssn: "463-08-2557",
  },
  {
    department: "Human Resources",
    company: "Fivebridge",
    gender: "Agender",
    language: "Montenegrin",
    first_name: "Boy",
    ssn: "640-14-8909",
  },
  {
    department: "Training",
    company: "Kwilith",
    gender: "Female",
    language: "Spanish",
    first_name: "Sada",
    ssn: "617-40-5405",
  },
  {
    department: "Legal",
    company: "InnoZ",
    gender: "Male",
    language: "Dzongkha",
    first_name: "Bentlee",
    ssn: "860-78-6332",
  },
  {
    department: "Training",
    company: "Rooxo",
    gender: "Female",
    language: "Kannada",
    first_name: "Prudy",
    ssn: "753-17-8871",
  },
  {
    department: "Legal",
    company: "Npath",
    gender: "Male",
    language: "Bengali",
    first_name: "Christopher",
    ssn: "173-28-3813",
  },
  {
    department: "Business Development",
    company: "Quamba",
    gender: "Male",
    language: "Assamese",
    first_name: "Cornie",
    ssn: "638-27-8808",
  },
  {
    department: "Accounting",
    company: "Oyoloo",
    gender: "Female",
    language: "Aymara",
    first_name: "Sheila",
    ssn: "738-45-0999",
  },
  {
    department: "Human Resources",
    company: "Flashset",
    gender: "Female",
    language: "Georgian",
    first_name: "Rena",
    ssn: "477-71-2112",
  },
  {
    department: "Services",
    company: "Trudoo",
    gender: "Male",
    language: "Fijian",
    first_name: "Donaugh",
    ssn: "263-53-9699",
  },
  {
    department: "Sales",
    company: "Realcube",
    gender: "Male",
    language: "Aymara",
    first_name: "Dale",
    ssn: "152-59-1018",
  },
  {
    department: "Legal",
    company: "Blogtags",
    gender: "Male",
    language: "Gagauz",
    first_name: "Kirk",
    ssn: "348-73-9802",
  },
  {
    department: "Legal",
    company: "Rhycero",
    gender: "Male",
    language: "Korean",
    first_name: "Heinrik",
    ssn: "797-18-2504",
  },
  {
    department: "Human Resources",
    company: "BlogXS",
    gender: "Female",
    language: "Icelandic",
    first_name: "Kerry",
    ssn: "579-42-8811",
  },
  {
    department: "Training",
    company: "Riffpedia",
    gender: "Female",
    language: "Oriya",
    first_name: "Betty",
    ssn: "525-53-4332",
  },
  {
    department: "Human Resources",
    company: "Gabtype",
    gender: "Male",
    language: "Marathi",
    first_name: "Menard",
    ssn: "186-51-4148",
  },
  {
    department: "Training",
    company: "Minyx",
    gender: "Male",
    language: "French",
    first_name: "Caddric",
    ssn: "386-90-6593",
  },
  {
    department: "Research and Development",
    company: "Ailane",
    gender: "Male",
    language: "Kurdish",
    first_name: "Ashton",
    ssn: "569-61-8944",
  },
  {
    department: "Training",
    company: "Oyope",
    gender: "Female",
    language: "Croatian",
    first_name: "Nerty",
    ssn: "814-43-7932",
  },
  {
    department: "Product Management",
    company: "Topiczoom",
    gender: "Male",
    language: "Tetum",
    first_name: "Frans",
    ssn: "201-85-7640",
  },
  {
    department: "Support",
    company: "Eimbee",
    gender: "Genderqueer",
    language: "Guaraní",
    first_name: "Jennine",
    ssn: "142-46-0642",
  },
  {
    department: "Business Development",
    company: "Jetpulse",
    gender: "Female",
    language: "Malay",
    first_name: "Riane",
    ssn: "106-92-4721",
  },
  {
    department: "Legal",
    company: "Fivebridge",
    gender: "Female",
    language: "Malay",
    first_name: "Peta",
    ssn: "746-68-9898",
  },
  {
    department: "Engineering",
    company: "Wikivu",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Shae",
    ssn: "318-25-1750",
  },
  {
    department: "Marketing",
    company: "Myworks",
    gender: "Female",
    language: "Nepali",
    first_name: "Laryssa",
    ssn: "771-87-1672",
  },
  {
    department: "Human Resources",
    company: "Jazzy",
    gender: "Genderqueer",
    language: "Armenian",
    first_name: "Raven",
    ssn: "489-44-2551",
  },
  {
    department: "Services",
    company: "Brightbean",
    gender: "Male",
    language: "Somali",
    first_name: "Creighton",
    ssn: "202-73-5034",
  },
  {
    department: "Legal",
    company: "Thoughtblab",
    gender: "Female",
    language: "Khmer",
    first_name: "Tiena",
    ssn: "732-45-3448",
  },
  {
    department: "Engineering",
    company: "Avavee",
    gender: "Female",
    language: "Māori",
    first_name: "Barbey",
    ssn: "438-91-0842",
  },
  {
    department: "Business Development",
    company: "Feedfish",
    gender: "Male",
    language: "Fijian",
    first_name: "Lamond",
    ssn: "289-56-7218",
  },
  {
    department: "Accounting",
    company: "Gabspot",
    gender: "Non-binary",
    language: "French",
    first_name: "Monro",
    ssn: "894-69-4796",
  },
  {
    department: "Business Development",
    company: "Skalith",
    gender: "Male",
    language: "Filipino",
    first_name: "Gay",
    ssn: "596-02-2966",
  },
  {
    department: "Engineering",
    company: "Brightbean",
    gender: "Female",
    language: "Dhivehi",
    first_name: "Carolyn",
    ssn: "384-07-0461",
  },
  {
    department: "Sales",
    company: "Roodel",
    gender: "Female",
    language: "Hindi",
    first_name: "Amandi",
    ssn: "163-60-8228",
  },
  {
    department: "Services",
    company: "Youbridge",
    gender: "Male",
    language: "Papiamento",
    first_name: "Archibold",
    ssn: "436-90-1509",
  },
  {
    department: "Training",
    company: "Realmix",
    gender: "Male",
    language: "Tamil",
    first_name: "Hussein",
    ssn: "276-79-8434",
  },
  {
    department: "Marketing",
    company: "Fatz",
    gender: "Female",
    language: "Italian",
    first_name: "Loraine",
    ssn: "256-65-4040",
  },
  {
    department: "Product Management",
    company: "BlogXS",
    gender: "Female",
    language: "Kazakh",
    first_name: "Teresa",
    ssn: "444-60-8165",
  },
  {
    department: "Support",
    company: "Camido",
    gender: "Female",
    language: "Tswana",
    first_name: "Annetta",
    ssn: "642-01-6813",
  },
  {
    department: "Product Management",
    company: "Kwimbee",
    gender: "Female",
    language: "Amharic",
    first_name: "Fiann",
    ssn: "205-44-7626",
  },
  {
    department: "Marketing",
    company: "Fliptune",
    gender: "Male",
    language: "Dhivehi",
    first_name: "Payton",
    ssn: "450-81-1529",
  },
  {
    department: "Sales",
    company: "Twinder",
    gender: "Male",
    language: "Bulgarian",
    first_name: "Arturo",
    ssn: "654-99-0977",
  },
  {
    department: "Business Development",
    company: "Linklinks",
    gender: "Genderqueer",
    language: "Kashmiri",
    first_name: "Flossi",
    ssn: "157-89-9907",
  },
  {
    department: "Legal",
    company: "Oyoyo",
    gender: "Female",
    language: "Tajik",
    first_name: "Nelie",
    ssn: "497-37-5605",
  },
  {
    department: "Support",
    company: "Brightbean",
    gender: "Polygender",
    language: "Haitian Creole",
    first_name: "Briant",
    ssn: "305-53-4940",
  },
  {
    department: "Accounting",
    company: "Twitternation",
    gender: "Male",
    language: "Sotho",
    first_name: "Ade",
    ssn: "876-03-4820",
  },
  {
    department: "Accounting",
    company: "Mynte",
    gender: "Female",
    language: "Gagauz",
    first_name: "Jeanette",
    ssn: "429-20-0382",
  },
  {
    department: "Training",
    company: "Zoonder",
    gender: "Agender",
    language: "Indonesian",
    first_name: "Washington",
    ssn: "373-29-8950",
  },
  {
    department: "Sales",
    company: "Kayveo",
    gender: "Male",
    language: "Persian",
    first_name: "Lowell",
    ssn: "668-97-7598",
  },
  {
    department: "Business Development",
    company: "Eamia",
    gender: "Agender",
    language: "Telugu",
    first_name: "Leonie",
    ssn: "232-01-5499",
  },
  {
    department: "Support",
    company: "Twitternation",
    gender: "Female",
    language: "Haitian Creole",
    first_name: "Vikky",
    ssn: "634-01-9833",
  },
  {
    department: "Legal",
    company: "Rhyzio",
    gender: "Male",
    language: "Tetum",
    first_name: "Kelwin",
    ssn: "811-12-9489",
  },
  {
    department: "Support",
    company: "Innotype",
    gender: "Male",
    language: "French",
    first_name: "Prent",
    ssn: "156-42-2144",
  },
  {
    department: "Business Development",
    company: "Camimbo",
    gender: "Male",
    language: "Latvian",
    first_name: "Martino",
    ssn: "540-70-9444",
  },
  {
    department: "Legal",
    company: "Mita",
    gender: "Male",
    language: "Quechua",
    first_name: "Morris",
    ssn: "223-75-4360",
  },
  {
    department: "Legal",
    company: "Yoveo",
    gender: "Female",
    language: "Filipino",
    first_name: "Lynna",
    ssn: "252-07-2797",
  },
  {
    department: "Human Resources",
    company: "Zava",
    gender: "Male",
    language: "Chinese",
    first_name: "Nickolas",
    ssn: "613-34-9012",
  },
  {
    department: "Support",
    company: "Jabbersphere",
    gender: "Female",
    language: "Swahili",
    first_name: "Genevra",
    ssn: "859-48-9409",
  },
  {
    department: "Engineering",
    company: "Yambee",
    gender: "Female",
    language: "Kashmiri",
    first_name: "Florrie",
    ssn: "343-22-0307",
  },
  {
    department: "Engineering",
    company: "Eabox",
    gender: "Male",
    language: "Spanish",
    first_name: "Norman",
    ssn: "397-46-8063",
  },
  {
    department: "Accounting",
    company: "Camido",
    gender: "Male",
    language: "Bengali",
    first_name: "Yorgo",
    ssn: "371-99-1207",
  },
  {
    department: "Legal",
    company: "Skajo",
    gender: "Polygender",
    language: "Oriya",
    first_name: "Moyna",
    ssn: "160-89-9283",
  },
  {
    department: "Human Resources",
    company: "Kare",
    gender: "Male",
    language: "Czech",
    first_name: "Darbee",
    ssn: "624-82-1554",
  },
  {
    department: "Business Development",
    company: "Skimia",
    gender: "Female",
    language: "Kannada",
    first_name: "Enid",
    ssn: "439-75-9332",
  },
  {
    department: "Research and Development",
    company: "Riffpedia",
    gender: "Male",
    language: "Japanese",
    first_name: "Gayelord",
    ssn: "508-83-9989",
  },
  {
    department: "Human Resources",
    company: "Voonyx",
    gender: "Female",
    language: "Irish Gaelic",
    first_name: "Arlyn",
    ssn: "197-46-5918",
  },
  {
    department: "Support",
    company: "Jaxspan",
    gender: "Male",
    language: "Swati",
    first_name: "Francklyn",
    ssn: "552-09-1191",
  },
  {
    department: "Marketing",
    company: "Avaveo",
    gender: "Female",
    language: "Georgian",
    first_name: "Fanchon",
    ssn: "530-89-7285",
  },
  {
    department: "Research and Development",
    company: "Eimbee",
    gender: "Male",
    language: "Northern Sotho",
    first_name: "Harv",
    ssn: "104-81-0902",
  },
  {
    department: "Accounting",
    company: "Yadel",
    gender: "Female",
    language: "Yiddish",
    first_name: "Malinda",
    ssn: "335-44-7778",
  },
  {
    department: "Training",
    company: "Fivebridge",
    gender: "Female",
    language: "Finnish",
    first_name: "Sammy",
    ssn: "751-71-2541",
  },
  {
    department: "Legal",
    company: "Tagopia",
    gender: "Female",
    language: "Oriya",
    first_name: "Marylynne",
    ssn: "386-95-7929",
  },
  {
    department: "Business Development",
    company: "Realbridge",
    gender: "Female",
    language: "Dhivehi",
    first_name: "Tricia",
    ssn: "747-06-4926",
  },
  {
    department: "Product Management",
    company: "Devbug",
    gender: "Male",
    language: "Northern Sotho",
    first_name: "Cornell",
    ssn: "399-12-7223",
  },
  {
    department: "Services",
    company: "Yata",
    gender: "Male",
    language: "Bislama",
    first_name: "Anders",
    ssn: "706-64-1676",
  },
  {
    department: "Product Management",
    company: "Mynte",
    gender: "Male",
    language: "Azeri",
    first_name: "Yule",
    ssn: "322-51-6942",
  },
  {
    department: "Sales",
    company: "Thoughtstorm",
    gender: "Male",
    language: "Belarusian",
    first_name: "Justinian",
    ssn: "160-58-4728",
  },
  {
    department: "Human Resources",
    company: "Fivespan",
    gender: "Polygender",
    language: "Irish Gaelic",
    first_name: "Feliza",
    ssn: "303-71-7700",
  },
  {
    department: "Product Management",
    company: "Cogilith",
    gender: "Male",
    language: "German",
    first_name: "Waylan",
    ssn: "792-59-4174",
  },
  {
    department: "Product Management",
    company: "Skyndu",
    gender: "Male",
    language: "Amharic",
    first_name: "Olivier",
    ssn: "852-79-8108",
  },
  {
    department: "Business Development",
    company: "Lazz",
    gender: "Male",
    language: "Mongolian",
    first_name: "Kermie",
    ssn: "401-01-5683",
  },
  {
    department: "Legal",
    company: "Shufflebeat",
    gender: "Male",
    language: "Haitian Creole",
    first_name: "Clerc",
    ssn: "167-58-1220",
  },
  {
    department: "Training",
    company: "Twimbo",
    gender: "Male",
    language: "Burmese",
    first_name: "Chadd",
    ssn: "749-51-0967",
  },
  {
    department: "Human Resources",
    company: "Bluezoom",
    gender: "Male",
    language: "Finnish",
    first_name: "Godwin",
    ssn: "492-40-4020",
  },
  {
    department: "Business Development",
    company: "Kare",
    gender: "Female",
    language: "Marathi",
    first_name: "Camala",
    ssn: "691-30-9584",
  },
  {
    department: "Sales",
    company: "Feedfish",
    gender: "Male",
    language: "Kurdish",
    first_name: "Free",
    ssn: "346-88-2315",
  },
  {
    department: "Engineering",
    company: "Skippad",
    gender: "Female",
    language: "Catalan",
    first_name: "Ruthy",
    ssn: "576-13-1431",
  },
  {
    department: "Legal",
    company: "Twinder",
    gender: "Male",
    language: "Malay",
    first_name: "Brooke",
    ssn: "870-70-0588",
  },
  {
    department: "Marketing",
    company: "Leenti",
    gender: "Male",
    language: "Somali",
    first_name: "Llywellyn",
    ssn: "291-20-6068",
  },
  {
    department: "Accounting",
    company: "Skippad",
    gender: "Male",
    language: "Telugu",
    first_name: "Irvine",
    ssn: "297-69-6941",
  },
  {
    department: "Services",
    company: "Midel",
    gender: "Female",
    language: "Italian",
    first_name: "Sharlene",
    ssn: "252-87-5030",
  },
  {
    department: "Business Development",
    company: "Twiyo",
    gender: "Female",
    language: "Montenegrin",
    first_name: "Phil",
    ssn: "101-53-5883",
  },
  {
    department: "Sales",
    company: "Feedbug",
    gender: "Female",
    language: "Malayalam",
    first_name: "Jillene",
    ssn: "451-29-4407",
  },
  {
    department: "Human Resources",
    company: "Zoovu",
    gender: "Male",
    language: "Mongolian",
    first_name: "Fernando",
    ssn: "481-48-7856",
  },
  {
    department: "Product Management",
    company: "Voonix",
    gender: "Male",
    language: "Dzongkha",
    first_name: "Osborn",
    ssn: "747-46-4403",
  },
  {
    department: "Product Management",
    company: "Avavee",
    gender: "Female",
    language: "Telugu",
    first_name: "Abby",
    ssn: "248-90-8082",
  },
  {
    department: "Marketing",
    company: "Feedspan",
    gender: "Male",
    language: "Malayalam",
    first_name: "Axel",
    ssn: "710-37-4631",
  },
  {
    department: "Support",
    company: "Jetwire",
    gender: "Male",
    language: "Assamese",
    first_name: "Abeu",
    ssn: "441-81-7185",
  },
  {
    department: "Legal",
    company: "Fivespan",
    gender: "Female",
    language: "Romanian",
    first_name: "Flossy",
    ssn: "399-43-6695",
  },
  {
    department: "Training",
    company: "Eire",
    gender: "Male",
    language: "Haitian Creole",
    first_name: "Brion",
    ssn: "590-62-3838",
  },
  {
    department: "Human Resources",
    company: "Twiyo",
    gender: "Bigender",
    language: "Albanian",
    first_name: "Rose",
    ssn: "727-60-9066",
  },
  {
    department: "Research and Development",
    company: "Yodo",
    gender: "Male",
    language: "Tajik",
    first_name: "Richy",
    ssn: "269-41-3167",
  },
  {
    department: "Engineering",
    company: "Tagcat",
    gender: "Female",
    language: "Yiddish",
    first_name: "Ermengarde",
    ssn: "587-49-2463",
  },
  {
    department: "Engineering",
    company: "Minyx",
    gender: "Male",
    language: "Swati",
    first_name: "Lambert",
    ssn: "137-50-1659",
  },
  {
    department: "Accounting",
    company: "Rhyloo",
    gender: "Male",
    language: "Thai",
    first_name: "Isador",
    ssn: "777-11-7921",
  },
  {
    department: "Research and Development",
    company: "Tazzy",
    gender: "Female",
    language: "Haitian Creole",
    first_name: "Denna",
    ssn: "530-06-9141",
  },
  {
    department: "Marketing",
    company: "Livetube",
    gender: "Female",
    language: "Telugu",
    first_name: "Colleen",
    ssn: "781-28-3251",
  },
  {
    department: "Research and Development",
    company: "Kayveo",
    gender: "Bigender",
    language: "Czech",
    first_name: "Rhodie",
    ssn: "311-01-5320",
  },
  {
    department: "Product Management",
    company: "Demizz",
    gender: "Female",
    language: "Dutch",
    first_name: "Tasia",
    ssn: "851-01-8709",
  },
];

// 1. Engineering 부서만 가져와서 콘솔 출력
const engineer = data.filter((x) => x.department.includes("Engineering"));
console.log(engineer);

// 2. 성별이 남성이고 일본어 쓰면, 어디부서이고 이름만 가져와서 출력
const dg = data
  .filter((x) => x.gender === "Male" && x.language === "Japanese")
  .map((x) => {
    return { department: x.department, first_name: x.first_name };
  });
console.log(dg);

// 3. ssn에서 맨 뒷 마지막 자리가 짝수이고, 퍼스트이름이 K,B,S로 시작하는 사람만 가져오기
const ssnName = data.filter(
  (x) =>
    Number(x.ssn[x.ssn.length - 1]) % 2 == 0 &&
    ["K", "B", "S"].some((y) => x.first_name.startsWith(y))
);
console.log(ssnName);

// Korean, Japanese, Chinese 중 사용하고
// 성별 여성
// ssn에서 앞에 있는 세 숫자의 합이 10 이상
const shit = data
  .filter(
    (x) =>
      x.language === "Korean" ||
      x.language === "Japanese" ||
      x.language === "Chinese"
  )
  .filter((x) => x.gender === "Female")
  .filter((x) => {
    const arr = [...x.ssn];
    return Number(arr[0]) + Number(arr[1]) + Number(arr[2]) > 10;
  });
console.log(shit);
